### ISSUE TITLE
[BUG]: shell script error

### ISSUE THREAD

**Issue by linyuqing222** [shinokada/svelte-next#1]
### Description of the bug

When using `awesome` to install `svelte-next`, then run `svelte-next -h` will appear error.
```bash
/home/kevinlin/.local/share/bin/svelte-next: 110: /home/kevinlin/.local/share/awesome/svelte-next/lib/utils.sh: Syntax error: "(" unexpected
```

### Steps To Reproduce

1. [install `awesome` and `svelte-next`](https://github.com/shinokada/svelte-next#installation)
2. run `svelte-next -h`
3. See error

**Comment by shinokada** [comment]
What is your output of `awesome ls`?

**Comment by linyuqing222** [comment]
```bash
kevinlin@home:/web/dl$ awesome ls
svelte-next
awesome
```

Additionally I found that when running `awesome links` an error is displayed:
```bash
ls: cannot access '/home/kevinlin/bin': No such file or directory
```
I'm not sure if this has anything to do with it.

**Comment by shinokada** [comment]
What is your outputs of `npx envinfo --system --binaries`?

And output of `awesome --version`?

Do you have `export PATH=$HOME/.local/share/bin:$PATH` in your terminal config file, like `.bashrc` or `.zshrc`?

**Comment by linyuqing222** [comment]
`npx envinfo --system --binaries`
```bash
  System:
    OS: Linux 5.15 Ubuntu 24.04 LTS 24.04 LTS (Noble Numbat)
    CPU: (8) x64 11th Gen Intel(R) Core(TM) i7-11370H @ 3.30GHz
    Memory: 3.36 GB / 7.65 GB
    Container: Yes
    Shell: 5.2.21 - /bin/bash
  Binaries:
    Node: 20.14.0 - /usr/bin/node
    Yarn: 3.6.3 - /usr/bin/yarn
    npm: 10.8.1 - /usr/bin/npm
    pnpm: 9.1.4 - /usr/bin/pnpm
    bun: 1.1.12 - ~/.bun/bin/bun
```
p.s. I'm in Ubuntu on WLS 2.

`awesome --version`
```bash
0.5.3
```

Yes, I has export in my .bashrc
If not export, It won't work.

Could this be caused by the need to use `set` commands to set or unset the values of shell options and positional parameters?

**Comment by shinokada** [comment]
Please update it and let me know.

```
awesome update svelte-next
```

**Comment by linyuqing222** [comment]
Ready to use!

By the way, the output of the last command
```bash
/home/kevinlin/.local/share/awesome/svelte-next/src/update.sh: line 107: jq: command not found
```
But that's okay. Doesn't seem to be relevant to the main function.
Thanks!

**Comment by shinokada** [comment]
Yes, it should work, but it is nice to have it for the final outputs.

You can install `jq`:

```
sudo apt-get update
sudo apt-get install jq
```
